target : complex.cpp complex_test.cpp /home/adi/LTTS/C++/Workbook2/include/complex.h  
	g++ complex.cpp complex_test.cpp /home/adi/LTTS/C++/Workbook2/include/complex.h -lgtest -lgtest_main -lpthread -o box.out 

run : target
	./complex.out


