target : complex.cpp complex_test.cpp /home/adi/LTTS/C++/Workbook4/include/complex.h
	g++ complex.cpp complex_test.cpp /home/adi/LTTS/C++/Workbook4/include/complex.h -lgtest -lgtest_main -lpthread -o complex.out 

run : target
	./complex.out

