target : box.cpp box_test.cpp /home/adi/LTTS/C++/Workbook1/include/Box.h  
	g++ box.cpp box_test.cpp /home/adi/LTTS/C++/Workbook1/include/Box.h -lgtest -lgtest_main -lpthread -o box.out 

run : target
	./box.out


