target : circle.cpp polygon.cpp rectangle.cpp shapes_test.cpp triangle.cpp /home/adi/LTTS/C++/Workbook3/include/circle.h  /home/adi/LTTS/C++/Workbook3/include/polygon.h /home/adi/LTTS/C++/Workbook3/include/rectangle.h /home/adi/LTTS/C++/Workbook3/include/shape.h /home/adi/LTTS/C++/Workbook3/include/triangle.h
	g++ circle.cpp polygon.cpp rectangle.cpp shapes_test.cpp triangle.cpp /home/adi/LTTS/C++/Workbook3/include/circle.h  /home/adi/LTTS/C++/Workbook3/include/polygon.h /home/adi/LTTS/C++/Workbook3/include/rectangle.h /home/adi/LTTS/C++/Workbook3/include/shape.h /home/adi/LTTS/C++/Workbook3/include/triangle.h -lgtest -lgtest_main -lpthread -o box.out 

run : target
	./shape.out


